import { useState } from "react";
import { Input, Modal, Popconfirm, Tag } from "antd";
import { toast } from "react-toastify";
import { PrimaryButton } from "@/components/ui";
import { DeleteModal } from "@/components/common/Modals";
import { getApiError } from "@/lib/api";
import LeadSectionCard from "@/modules/leads/components/details/LeadSectionCard";
import AddPaymentModal from "@/modules/payments/components/AddPaymentModal";
import ReceiptViewModal from "@/modules/payments/components/ReceiptViewModal";
import {
  useChangeLeadServiceOfferStatusMutation,
  useDeleteLeadServiceOfferMutation,
  useGenerateLeadServiceOfferMutation,
  useGetServiceOfferContextQuery,
  useListLeadServiceOffersQuery,
  useRecordOfferInstallmentPaymentMutation,
  type OfferStatusAction,
} from "../api/packagesApi";
import type { OfferLineKind, ServiceOfferRecord, ServiceOfferStatus } from "../types";
import { formatMoney } from "../utils/offerCalculator";
import ServiceOfferEditor from "./ServiceOfferEditor";

const STATUS_TAG: Record<ServiceOfferStatus, { label: string; color: string }> = {
  DRAFT: { label: "Draft", color: "default" },
  GENERATED: { label: "Generated", color: "blue" },
  SENT: { label: "Sent / Offered", color: "geekblue" },
  ACCEPTED: { label: "Accepted", color: "green" },
  PAYMENT_PENDING: { label: "Payment Pending", color: "gold" },
  PARTIALLY_PAID: { label: "Partially Paid", color: "orange" },
  PAID: { label: "Paid", color: "success" },
  REJECTED: { label: "Rejected", color: "red" },
  EXPIRED: { label: "Expired", color: "volcano" },
  CANCELLED: { label: "Cancelled", color: "default" },
};

const ACTIVE_STATUSES: ServiceOfferStatus[] = ["ACCEPTED", "PAYMENT_PENDING", "PARTIALLY_PAID", "PAID"];
const OPEN_STATUSES: ServiceOfferStatus[] = ["DRAFT", "GENERATED", "SENT"];
const CLOSED_STATUSES: ServiceOfferStatus[] = ["REJECTED", "EXPIRED", "CANCELLED"];

const KIND_LABEL: Record<OfferLineKind, string> = {
  PACKAGE_INCLUDED: "Included",
  PACKAGE_OPTIONAL: "Optional",
  SERVICE: "Service",
  ADDITIONAL: "Additional",
  CUSTOM_SERVICE: "Custom service",
  CUSTOM_CHARGE: "Custom charge",
};

const ACTION_COPY: Record<OfferStatusAction, { title: string; okText: string; description?: string }> = {
  send: { title: "Mark this offer as sent?", okText: "Mark as Sent", description: "Record that the offer has been shared with the student." },
  accept: {
    title: "Mark this offer as accepted?",
    okText: "Mark as Accepted",
    description: "The accepted version, amount, and services are recorded and the offer can no longer be edited.",
  },
  reject: { title: "Mark this offer as rejected", okText: "Mark as Rejected" },
  cancel: { title: "Cancel this offer", okText: "Cancel Offer" },
};

function dateTime(value: string | null) {
  return value ? new Date(value).toLocaleString() : "—";
}

function dateOnly(value: string | null) {
  return value ? new Date(value).toLocaleDateString() : "—";
}

function Row({ label, value, strong }: { label: string; value: string; strong?: boolean }) {
  return (
    <div className={`flex justify-between gap-3 ${strong ? "font-semibold text-[#17324f] dark:text-text-strong" : ""}`}>
      <span>{label}</span>
      <span>{value}</span>
    </div>
  );
}

function statusLine(offer: ServiceOfferRecord) {
  switch (offer.status) {
    case "DRAFT":
      return `Saved by ${offer.updatedBy?.fullName || offer.createdBy?.fullName || "—"} · ${dateTime(offer.updatedAt)}`;
    case "GENERATED":
      return `Generated by ${offer.generatedBy?.fullName || "—"} · ${dateTime(offer.generatedAt)}`;
    case "SENT":
      return `Sent by ${offer.sentBy?.fullName || "—"} · ${dateTime(offer.sentAt)}${
        offer.validUntil ? ` · Valid until ${dateOnly(offer.validUntil)}` : ""
      }`;
    case "REJECTED":
      return `Rejected · ${dateTime(offer.rejectedAt)}${offer.rejectionReason ? ` — ${offer.rejectionReason}` : ""}`;
    case "EXPIRED":
      return `Expired · validity ended ${dateOnly(offer.validUntil)}`;
    case "CANCELLED":
      return `Cancelled by ${offer.cancelledBy?.fullName || "—"} · ${dateTime(offer.cancelledAt)}${
        offer.cancelReason ? ` — ${offer.cancelReason}` : ""
      }`;
    default:
      return `Accepted by ${offer.acceptedBy?.fullName || "—"} · ${dateTime(offer.acceptedAt)}`;
  }
}

function OfferDetails({
  offer,
  canRecordPayment,
  paying,
  onPay,
}: {
  offer: ServiceOfferRecord;
  canRecordPayment: boolean;
  paying: boolean;
  onPay: (installmentId: string) => void;
}) {
  const discounted = Number(offer.lineDiscountTotal) > 0 || Number(offer.overallDiscountAmount) > 0;
  const payable = offer.status === "PAYMENT_PENDING" || offer.status === "PARTIALLY_PAID";
  return (
    <div className="grid gap-4 text-sm">
      <div className="grid gap-1.5">
        {offer.packageName ? (
          <Row
            label={`Package: ${offer.packageName} — Version ${offer.versionNumber}`}
            value={formatMoney(offer.packagePrice)}
          />
        ) : null}
        {offer.packageName && offer.packageDefaultPrice !== offer.packagePrice ? (
          <p className="m-0 text-xs text-text-muted">Default package price {formatMoney(offer.packageDefaultPrice)}</p>
        ) : null}
        {offer.items.map((item) => (
          <div key={item.id} className="flex justify-between gap-3 text-[#5d6b7c]">
            <span>
              {item.serviceName}
              <span className="text-text-muted">
                {" "}
                · {KIND_LABEL[item.kind]}
                {item.kind !== "PACKAGE_INCLUDED" && item.quantity > 1 ? ` · ${item.quantity} × ${formatMoney(item.offeredPrice)}` : ""}
              </span>
              {item.defaultPrice && item.defaultPrice !== item.offeredPrice && item.kind !== "PACKAGE_INCLUDED" ? (
                <span className="block text-xs text-text-muted">
                  Default {formatMoney(item.defaultPrice)} → Offered {formatMoney(item.offeredPrice)}
                </span>
              ) : null}
              {Number(item.discountAmount) > 0 ? (
                <span className="block text-xs text-text-muted">
                  Discount {item.discountType === "PERCENTAGE" ? `${Number(item.discountValue)}%` : formatMoney(item.discountValue)} —{" "}
                  {item.discountReason}
                </span>
              ) : null}
            </span>
            <span>{item.kind === "PACKAGE_INCLUDED" ? "In package" : formatMoney(item.lineTotal)}</span>
          </div>
        ))}
        {Number(offer.fileOpeningCharge) > 0 ? <Row label="File opening charge" value={formatMoney(offer.fileOpeningCharge)} /> : null}
      </div>
      <div className="grid gap-1.5 rounded-xl bg-[#f8fafc] px-4 py-3 dark:bg-transparent">
        <Row label="Gross amount" value={formatMoney(offer.grossTotal)} />
        {discounted ? <Row label="Line item discount" value={`− ${formatMoney(offer.lineDiscountTotal)}`} /> : null}
        <Row label="Subtotal" value={formatMoney(offer.subtotal)} />
        {discounted ? (
          <Row
            label={`Overall discount${offer.overallDiscountReason ? ` — ${offer.overallDiscountReason}` : ""}`}
            value={`− ${formatMoney(offer.overallDiscountAmount)}`}
          />
        ) : null}
        <Row label="Final payable" value={formatMoney(offer.finalPayable)} strong />
        {offer.initialPayment ? (
          <>
            <Row label="Initial payment" value={formatMoney(offer.initialPayment)} />
            <Row label="Remaining due" value={formatMoney(offer.remainingAfterInitial)} />
          </>
        ) : null}
        {offer.expectedDealValue !== offer.finalPayable ? (
          <Row label="Expected deal value" value={formatMoney(offer.expectedDealValue)} />
        ) : null}
        {ACTIVE_STATUSES.includes(offer.status) ? (
          <>
            <Row label="Received" value={formatMoney(offer.paidAmount)} />
            <Row label="Due" value={formatMoney(offer.dueAmount)} strong />
          </>
        ) : null}
      </div>
      {offer.installments.length ? (
        <div className="grid gap-1.5">
          <p className="m-0 font-medium">Payment plan</p>
          {offer.installments.map((item) => (
            <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 text-[#5d6b7c]">
              <span>
                Payment {item.sequence}: {item.purpose}
                {item.dueDate ? <span className="text-text-muted"> · due {item.dueDate}</span> : null}
                {item.paidAt ? (
                  <span className="block text-xs text-text-muted">
                    Received {dateTime(item.paidAt)}
                    {item.paidBy ? ` by ${item.paidBy.fullName}` : ""}
                  </span>
                ) : null}
              </span>
              <span className="flex items-center gap-2">
                {formatMoney(item.amount)}
                <Tag color={item.status === "PAID" ? "success" : item.status === "PARTIAL" ? "orange" : "default"}>
                  {item.status === "PAID" ? "Paid" : item.status === "PARTIAL" ? "Partial" : "Pending"}
                </Tag>
                {canRecordPayment && payable && item.status !== "PAID" ? (
                  <Popconfirm
                    title="Record this payment as received?"
                    okText="Record Payment"
                    onConfirm={() => onPay(item.id)}
                  >
                    <PrimaryButton type="button" size="sm" variant="outline" label="Record Payment" loading={paying} />
                  </Popconfirm>
                ) : null}
              </span>
            </div>
          ))}
        </div>
      ) : null}
      {offer.statusHistory.length ? (
        <div className="grid gap-1.5">
          <p className="m-0 font-medium">Status history</p>
          <ol className="m-0 grid gap-1 pl-4 text-xs text-[#5d6b7c]">
            {offer.statusHistory.map((entry) => (
              <li key={entry.id}>
                {entry.fromStatus ? `${STATUS_TAG[entry.fromStatus].label} → ` : "Created as "}
                {STATUS_TAG[entry.toStatus].label}
                <span className="text-text-muted">
                  {" "}
                  · {entry.changedBy?.fullName || "System"} · {dateTime(entry.createdAt)}
                  {entry.reason ? ` — ${entry.reason}` : ""}
                </span>
              </li>
            ))}
          </ol>
        </div>
      ) : null}
    </div>
  );
}

type ReasonPrompt = { offer: ServiceOfferRecord; action: "reject" | "cancel" };

export default function LeadPackageOfferPanel({
  leadId,
  leadName,
  leadCode,
  canOffer,
}: {
  leadId: string;
  leadName: string;
  leadCode: string;
  canOffer: boolean;
}) {
  const { data, isFetching, isError } = useListLeadServiceOffersQuery(leadId);
  const { data: context, isFetching: contextLoading } = useGetServiceOfferContextQuery(leadId, { skip: !canOffer });
  const [generateOffer, { isLoading: generating }] = useGenerateLeadServiceOfferMutation();
  const [deleteOffer, { isLoading: deleting }] = useDeleteLeadServiceOfferMutation();
  const [changeStatus, { isLoading: changing }] = useChangeLeadServiceOfferStatusMutation();
  const [recordPayment, { isLoading: paying }] = useRecordOfferInstallmentPaymentMutation();
  const [editor, setEditor] = useState<{ offer: ServiceOfferRecord | null; revise: boolean } | null>(null);
  const [expanded, setExpanded] = useState<string | null>(null);
  const [prompt, setPrompt] = useState<ReasonPrompt | null>(null);
  const [reason, setReason] = useState("");
  const [deleteTarget, setDeleteTarget] = useState<ServiceOfferRecord | null>(null);
  const [payOffer, setPayOffer] = useState<ServiceOfferRecord | null>(null);
  const [receiptId, setReceiptId] = useState<string | null>(null);

  const offers = data?.offers || [];
  const canRecordPayment = Boolean(context?.permissions.canRecordPayment);

  async function run(task: () => Promise<{ message: string }>, fallback: string) {
    try {
      const result = await task();
      toast.success(result.message);
      return true;
    } catch (error) {
      toast.error(getApiError(error, fallback));
      return false;
    }
  }

  function generate(offer: ServiceOfferRecord) {
    void run(() => generateOffer({ leadId, offerId: offer.id }).unwrap(), "Unable to save the service offer. Please try again.");
  }

  async function confirmDelete() {
    if (!deleteTarget || deleting) return;
    const ok = await run(
      () => deleteOffer({ leadId, offerId: deleteTarget.id }).unwrap(),
      "Unable to delete the draft offer. Please try again.",
    );
    if (ok) setDeleteTarget(null);
  }

  function transition(offer: ServiceOfferRecord, action: OfferStatusAction, withReason?: string) {
    return run(
      () => changeStatus({ leadId, offerId: offer.id, action, reason: withReason }).unwrap(),
      "This offer status change is not allowed.",
    );
  }

  function pay(offer: ServiceOfferRecord, installmentId: string) {
    void run(
      () => recordPayment({ leadId, offerId: offer.id, installmentId }).unwrap(),
      "Unable to record the payment. Please try again.",
    );
  }

  function openPrompt(offer: ServiceOfferRecord, action: ReasonPrompt["action"]) {
    setReason("");
    setPrompt({ offer, action });
  }

  async function submitPrompt() {
    if (!prompt) return;
    const trimmed = reason.trim();
    if (prompt.action === "cancel" && !trimmed) {
      toast.error("Please provide a reason for cancelling this offer.");
      return;
    }
    const done = await transition(prompt.offer, prompt.action, trimmed || undefined);
    if (done) setPrompt(null);
  }

  if (editor && context) {
    return (
      <ServiceOfferEditor
        key={`${editor.offer?.id || "new"}-${editor.revise ? "revise" : "edit"}`}
        leadId={leadId}
        context={context}
        offer={editor.offer}
        revise={editor.revise}
        onClose={() => setEditor(null)}
      />
    );
  }

  function confirmAction(offer: ServiceOfferRecord, action: "send" | "accept", primary = false) {
    const copy = ACTION_COPY[action];
    return (
      <Popconfirm
        key={action}
        title={copy.title}
        description={copy.description}
        okText={copy.okText}
        onConfirm={() => void transition(offer, action)}
      >
        <PrimaryButton type="button" size="sm" variant={primary ? undefined : "outline"} label={copy.okText} loading={changing} />
      </Popconfirm>
    );
  }

  function actions(offer: ServiceOfferRecord) {
    if (!canOffer) return null;
    const allows = (status: ServiceOfferStatus) => offer.allowedTransitions.includes(status);
    const otherOpen = offers.find((item) => item.id !== offer.id && OPEN_STATUSES.includes(item.status));
    const buttons = [];

    if (offer.status === "DRAFT" || offer.status === "GENERATED") {
      buttons.push(
        <PrimaryButton
          key="edit"
          type="button"
          size="sm"
          variant="outline"
          label="Edit"
          disabled={!context}
          onClick={() => setEditor({ offer, revise: false })}
        />,
      );
    }
    if (offer.status === "DRAFT") {
      buttons.push(
        <Popconfirm
          key="generate"
          title="Generate this offer?"
          description="The offer is finalized and becomes ready to send to the student."
          okText="Generate"
          onConfirm={() => generate(offer)}
        >
          <PrimaryButton type="button" size="sm" label="Generate Offer" loading={generating} />
        </Popconfirm>,
      );
    }
    if (allows("SENT")) buttons.push(confirmAction(offer, "send", true));
    if (allows("ACCEPTED")) buttons.push(confirmAction(offer, "accept", offer.status === "SENT"));
    if (allows("REJECTED")) {
      buttons.push(
        <PrimaryButton
          key="reject"
          type="button"
          size="sm"
          variant="outline"
          label="Mark as Rejected"
          onClick={() => openPrompt(offer, "reject")}
        />,
      );
    }
    if (offer.revisable && !otherOpen) {
      buttons.push(
        <PrimaryButton
          key="revise"
          type="button"
          size="sm"
          variant="outline"
          label="Create New Version"
          disabled={!context}
          onClick={() => setEditor({ offer, revise: true })}
        />,
      );
    }
    if (offer.status === "DRAFT" && !offer.revisedFrom && !offer.generatedAt) {
      buttons.push(
        <PrimaryButton
          key="delete"
          type="button"
          size="sm"
          variant="text"
          label="Delete"
          loading={deleting && deleteTarget?.id === offer.id}
          onClick={() => setDeleteTarget(offer)}
        />,
      );
    } else if (allows("CANCELLED")) {
      buttons.push(
        <PrimaryButton
          key="cancel"
          type="button"
          size="sm"
          variant="text"
          label="Cancel Offer"
          onClick={() => openPrompt(offer, "cancel")}
        />,
      );
    }
    return buttons;
  }

  return (
    <LeadSectionCard
      title="Service offers"
      extra={
        canOffer ? (
          <PrimaryButton
            type="button"
            size="sm"
            label="Create Offer"
            loading={contextLoading}
            disabled={!context}
            onClick={() => setEditor({ offer: null, revise: false })}
          />
        ) : null
      }
    >
      {isFetching && !data ? <p className="m-0 text-sm text-text-muted">Loading service offers…</p> : null}
      {isError ? <p className="m-0 text-sm text-danger">Unable to load service offers.</p> : null}
      {!isFetching && !isError && offers.length === 0 ? (
        <p className="m-0 text-sm text-text-muted">
          {canOffer
            ? "No service offer yet. Create one from a package or from individual services."
            : "No service offer yet. Creating one needs offer permission."}
        </p>
      ) : null}
      <div className="grid gap-3">
        {offers.map((offer) => {
          const status = STATUS_TAG[offer.status];
          const open = expanded === offer.id;
          const active = ACTIVE_STATUSES.includes(offer.status);
          const closed = CLOSED_STATUSES.includes(offer.status);
          return (
            <div
              key={offer.id}
              className={`rounded-xl border p-4 ${
                active ? "border-[#52c41a] bg-[#f3fbf6] dark:bg-transparent" : "border-[#e7eef5] dark:border-border"
              } ${closed ? "opacity-75" : ""}`}
            >
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div>
                  <p className="m-0 flex flex-wrap items-center gap-2 font-semibold text-[#17324f] dark:text-text-strong">
                    Offer V{offer.offerVersion}
                    <span className="font-normal text-text-muted">
                      · {offer.packageName ? `${offer.packageName} — Version ${offer.versionNumber}` : "Custom service offer"}
                    </span>
                    <Tag color={status.color}>{status.label}</Tag>
                    {active ? <Tag color="green">Active</Tag> : null}
                  </p>
                  <p className="m-0 text-xs text-text-muted">{statusLine(offer)}</p>
                  {offer.revisedFrom ? (
                    <p className="m-0 text-xs text-text-muted">Revised from Offer V{offer.revisedFrom.offerVersion}</p>
                  ) : null}
                </div>
                <div className="text-right">
                  <p className="m-0 font-semibold">{formatMoney(offer.finalPayable)}</p>
                  <p className="m-0 text-xs text-text-muted">
                    {active ? `Received ${formatMoney(offer.paidAmount)}` : "Final payable"}
                  </p>
                </div>
              </div>
              <div className="mt-3 flex flex-wrap gap-2">
                <PrimaryButton
                  type="button"
                  size="sm"
                  variant="text"
                  label={open ? "Hide details" : "View details"}
                  onClick={() => setExpanded(open ? null : offer.id)}
                />
                {canRecordPayment &&
                (offer.status === "PAYMENT_PENDING" ||
                  offer.status === "PARTIALLY_PAID" ||
                  offer.status === "ACCEPTED") &&
                Number(offer.dueAmount) > 0 ? (
                  <PrimaryButton
                    type="button"
                    size="sm"
                    label="Add Payment"
                    onClick={() => setPayOffer(offer)}
                  />
                ) : null}
                {actions(offer)}
              </div>
              {open ? (
                <div className="mt-3 border-t border-[#e7eef5] pt-3 dark:border-border">
                  <OfferDetails
                    offer={offer}
                    canRecordPayment={canRecordPayment}
                    paying={paying}
                    onPay={(installmentId) => pay(offer, installmentId)}
                  />
                </div>
              ) : null}
            </div>
          );
        })}
      </div>

      <Modal
        open={Boolean(prompt)}
        title={prompt ? `${ACTION_COPY[prompt.action].title} — Offer V${prompt.offer.offerVersion}` : ""}
        okText={prompt ? ACTION_COPY[prompt.action].okText : "OK"}
        okButtonProps={{ danger: prompt?.action === "cancel", loading: changing }}
        cancelText="Close"
        onOk={() => void submitPrompt()}
        onCancel={() => setPrompt(null)}
        destroyOnHidden
      >
        <p className="mb-2 text-sm text-text-muted">
          {prompt?.action === "cancel"
            ? "The offer and its history are kept, but it can no longer be accepted or paid."
            : "Record why the student declined this offer (optional)."}
        </p>
        <Input.TextArea
          rows={3}
          maxLength={500}
          placeholder={prompt?.action === "cancel" ? "Reason for cancellation (required)" : "Reason (optional)"}
          value={reason}
          onChange={(event) => setReason(event.target.value)}
        />
      </Modal>

      <DeleteModal
        open={Boolean(deleteTarget)}
        loading={deleting}
        title="Delete draft offer?"
        itemName={deleteTarget ? `Offer V${deleteTarget.offerVersion}` : "this draft offer"}
        onCancel={() => setDeleteTarget(null)}
        onConfirm={() => void confirmDelete()}
      />

      {payOffer ? (
        <AddPaymentModal
          open={Boolean(payOffer)}
          onClose={() => setPayOffer(null)}
          leadId={leadId}
          leadName={leadName}
          leadCode={leadCode}
          offerId={payOffer.id}
          offerLabel={`Offer V${payOffer.offerVersion}${payOffer.packageName ? ` · ${payOffer.packageName}` : ""}`}
          finalPayable={payOffer.finalPayable}
          previouslyPaid={payOffer.paidAmount}
          currentDue={payOffer.dueAmount}
          onSuccess={({ receiptId: nextReceipt }) => {
            if (nextReceipt) setReceiptId(nextReceipt);
          }}
        />
      ) : null}

      <ReceiptViewModal
        open={Boolean(receiptId)}
        receiptId={receiptId}
        onClose={() => setReceiptId(null)}
      />
    </LeadSectionCard>
  );
}
